<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Zeus.Communications" Version="ZEUS_VERSION" />
    <PackageReference Include="Zeus.Configuration" Version="ZEUS_VERSION" />
    <PackageReference Include="Zeus.Presentation.Wpf" Version="ZEUS_VERSION" />
    <PackageReference Include="Zeus.Protocols.Modbus" Version="ZEUS_VERSION" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="zeus.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
