<Project Sdk="Microsoft.NET.Sdk">

  <!-- JSON 配置示例：从 zeus.json 装载虚拟从站与点表。 -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Zeus.Samples.Console.Config</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Zeus.Configuration\Zeus.Configuration.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Hosting\Zeus.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.Modbus\Zeus.Protocols.Modbus.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.Mc\Zeus.Protocols.Mc.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.S7\Zeus.Protocols.S7.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.Fins\Zeus.Protocols.Fins.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.HostLink\Zeus.Protocols.HostLink.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.Mewtocol\Zeus.Protocols.Mewtocol.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.EtherNetIp\Zeus.Protocols.EtherNetIp.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.Dlt645\Zeus.Protocols.Dlt645.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.Iec104\Zeus.Protocols.Iec104.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.Mqtt\Zeus.Protocols.Mqtt.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.OpcUa\Zeus.Protocols.OpcUa.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.Snmp\Zeus.Protocols.Snmp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="zeus.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-fins-udp.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-fins-tcp.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-modbus-ascii.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-ethernet-ip.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-host-link.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-mewtocol.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-dlt645.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-iec104.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-snmp.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zeus-opcua.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
